name: fwtree
version: "1.4"
license: "GPL-2.0-or-later"
date: 2026-08-15
description: |
    Computing trees related to some pro-p-groups of finite width

authors:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Tobias Rossmann
      url: mailto:tobias.rossmann@googlemail.com

maintainers:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Tobias Rossmann
      url: mailto:tobias.rossmann@googlemail.com
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.12"

needed-pkgs:
    - name: "Polycyclic"
      version: ">=1.0"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "Autpgrp"
      version: ">=1.0"
      url: "https://gap-packages.github.io/autpgrp/"
    - name: "anupq"
      version: ">=1.0"
      url: "https://gap-packages.github.io/anupq/"

www: https://gap-packages.github.io/fwtree/
readme: README
packageinfo: https://gap-packages.github.io/fwtree/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/fwtree/releases/download/v1.4/fwtree-1.4.tar.gz

abstract: |
    The <span class="pkgname">fwtree</span> package contains some code related to the computation of trees corresponding to some groups of finite rank, width and obliquity.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    finite width, p-groups, trees.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>ER26</span>]   <b class='BibAuthor'>Eick, B. and Rossmann, T.</b>,
     <i class='BibTitle'>fwtree, Computing trees related to some pro-p-groups of finite width,
             Version 1.4</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/fwtree/">https://gap-packages.github.io/fwtree/</a></span>.
    </p>
    

bibtex: |
    @misc{ fwtree,
      author =           {Eick, B. and Rossmann, T.},
      title =            {{fwtree},    {Computing    trees   related   to   some
                          pro\texttt{\symbol{45}}p\texttt{\symbol{45}}groups  of
                          finite width}, {V}ersion 1.4},
      month =            {Aug},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/fwtree/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{fwtree/}}},
      keywords =         {finite width; p\texttt{\symbol{45}}groups; trees},
      printedkey =       {ER26}
    }

